name: demo-webapp-lb-guide images ci

on:
  push:
    paths:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Docker Build and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/demo-webapp-lb-guide:latest .
          docker push ghcr.io/robert0714/demo-webapp-lb-guide:latest